### ISSUE TITLE
Training a BAM

### ISSUE THREAD

**Issue by plab0n** [viralpoetry/bam#1]
In Training a BAM (Bidirectional Associative Memory) model, Xk is Input vector and is known. How can I find Yk for any particular Xk?

**Comment by viralpoetry** [comment]
it's associative memory, you have Xk, Yk pairs which you know and want to store. You create a matrix from them, than you can multiply matrix by Xk, which result in Yk vector and vice versa.

As wikipedia states:
```
BAM is hetero-associative, meaning given a pattern it can return another pattern
which is potentially of a different size.
```

**Comment by plab0n** [comment]
I have used your code for implementing BAM. But unfortunately its returning the same output for every pattern in recall. 
Here is the code: https://gist.github.com/plab0n/8f95f241fe6c11a911b80217dbf8140b

**Comment by viralpoetry** [comment]
@plab0n It's probably capacity problem, you could not fill many vectors to small matrix, otherwise there are collisions and it is unusable / error correcting codes must be used.
https://en.wikipedia.org/wiki/Bidirectional_associative_memory#Capacity

**Comment by plab0n** [comment]
@viralpoetry Thank you :) 
I got it :)
